### ISSUE TITLE
val_exprate=0 and save checkpoint

### ISSUE THREAD

**Issue by Ashleyyyi** [Green-Wood/BTTR#6]
hello!thanks for your time!
When I transfer some code in decoder or use it directly,the val_exprate are always be 0.000,I don't know why.
Another problem is,I noticed that this code don't have the function to save checkpoint or something.Can you give me some help?Thanks again!

**Comment by Green-Wood** [comment]
Hi, I think you may refer to issue #4, and see if you are encountered the same env problem.
For the second checkpoint problem, the pytorch lightning framework will automatically save the model with the highest val_ExpRate. Once your val_ExpRate increase, you will see a checkpoint file saved in your log folder.
In the `config.yaml`:
```
  - class_path: pytorch_lightning.callbacks.ModelCheckpoint
    init_args:
      save_top_k: 1
      monitor: val_ExpRate
      mode: max
      filename: '{epoch}-{step}-{val_ExpRate:.4f}'
```
